//screens/bill_model.dart
//data model for LA bill + user-generated summary.

class Bill {
  //data pulled from the LegiScan API
  final String billId;
  final String billNumber; //ie: HB 108
  final String title;
  final String latestAction;
  final String billUrl;
  final String billText; //full text to be summarized

  //data saved to firestore db & generated by gemini
  String? geminiSummary;
  String? firestoreDocId; //firestore ID for updates/deletion

  Bill({
    required this.billId,
    required this.billNumber,
    required this.title,
    required this.latestAction,
    required this.billUrl,
    required this.billText,
    this.geminiSummary,
    this.firestoreDocId,
  });

  //factory to create bill from firestore doc
  factory Bill.fromFirestore(Map<String, dynamic> data, String docId) {
    return Bill(
      billId: data['billId'] ?? '',
      billNumber: data['billNumber'] ?? '',
      title: data['title'] ?? 'No Title',
      latestAction: data['latestAction'] ?? 'No Action Data',
      billUrl: data['billUrl'] ?? '',
      billText: data['billText'] ?? '',
      geminiSummary: data['geminiSummary'],
      firestoreDocId: docId,
    );
  }

  //bill object to format for firestore db
  Map<String, dynamic> toFirestore() {
    return {
      'billId': billId,
      'billNumber': billNumber,
      'title': title,
      'latestAction': latestAction,
      'billUrl': billUrl,
      'billText': billText,
      'geminiSummary': geminiSummary,
      'timestamp': DateTime.now().toUtc().toIso8601String(),
    };
  }
}