// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDZH3flR9nnj-d3UrJcmfmB2KDHTMLugY',
    appId: '1:397952360707:web:d11fbba8ccf19d8d98c936',
    messagingSenderId: '397952360707',
    projectId: 'lawgic-9c1b5',
    authDomain: 'lawgic-9c1b5.firebaseapp.com',
    storageBucket: 'lawgic-9c1b5.firebasestorage.app',
    measurementId: 'G-BKLGW1HFPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADzwVKxFGfz-EAolNz25Oa6o5xlh_hpRA',
    appId: '1:397952360707:android:2f441661d9f96b8a98c936',
    messagingSenderId: '397952360707',
    projectId: 'lawgic-9c1b5',
    storageBucket: 'lawgic-9c1b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrSIYxfyhmYkAOfgFfwH4UDJcOniWMsbY',
    appId: '1:397952360707:ios:f6f899841b34187c98c936',
    messagingSenderId: '397952360707',
    projectId: 'lawgic-9c1b5',
    storageBucket: 'lawgic-9c1b5.firebasestorage.app',
    iosBundleId: 'com.example.lawgic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrSIYxfyhmYkAOfgFfwH4UDJcOniWMsbY',
    appId: '1:397952360707:ios:f6f899841b34187c98c936',
    messagingSenderId: '397952360707',
    projectId: 'lawgic-9c1b5',
    storageBucket: 'lawgic-9c1b5.firebasestorage.app',
    iosBundleId: 'com.example.lawgic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDZH3flR9nnj-d3UrJcmfmB2KDHTMLugY',
    appId: '1:397952360707:web:3eb22c8b5798b64698c936',
    messagingSenderId: '397952360707',
    projectId: 'lawgic-9c1b5',
    authDomain: 'lawgic-9c1b5.firebaseapp.com',
    storageBucket: 'lawgic-9c1b5.firebasestorage.app',
    measurementId: 'G-J4VX6J74EV',
  );

}